language: python

python:
  - 3.9

services:
  - xvfb
  
addons:
  chrome: stable

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3
  - python main.py &
  - sleep 3

script:
  - run -m unittest discover #&& coverage html
  - behave
  - coverage erase
  - pylint --output-format=text main.py

#after_success:
  #- coveralls
