language: python

python:
  - 3.9
  
addons:
  chrome: stable

branch: main

install:
  - gem install faraday -v 1.9.3
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - python -m unittest discover
  - coverage erase
  - pylint --output-format=text main.py
  - pylint --output-format=text setup.py
  - pylint --output-format=text forms
  - pylint --output-format=text logs
  - pylint --output-format=text models
  - pylint --output-format=text rest
  - pylint --output-format=text service
  - pylint --output-format=text tests
  - pylint --output-format=text views
  
after_success:
  - coveralls
