language: python
python:
  - 3.9
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run main.py -m pytest tests/
after_success:
  - coveralls
branches:
  only:
    - main
deploy:
  - provider: heroku
    app: departments-app
