language: python

python:
  - 3.9

services:
  - xvfb
  
addons:
  chrome: stable

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3
  - python main.py &
  - sleep 3

script:
  - behave
  - coverage erase
  - coverage run -m unittest discover && coverage html
  - pylint --output-format=text main.py

after_success:
  - coveralls
