language: python

python:
  - 3.9
  
addons:
  chrome: stable

install:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - coverage run -m unittest discover
  - coverage erase

after_success:
  - coveralls
