language: python

python:
  - 3.9
  
addons:
  chrome: stable

branch: main

install:
  - gem install faraday -v 1.9.3
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - python -m unittest discover
  - coverage erase
  - pylint --output-format=text main.py
  - coverage run main.py && coverage html
  - pytest
  
  
after_success:
  - coveralls
