language: python

python:
  - 3.9
  
addons:
  chrome: stable

install:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - python -m unittest discover
  - behave
  - coverage erase
  - coverage run --source=tests -m pytest tests/
  - pylint --output-format=text main.py

after_success:
  - coveralls
