"""empty message

Revision ID: 37acb0a75d8a
Revises: 
Create Date: 2022-01-16 16:32:29.914560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37acb0a75d8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('salary', sa.FLOAT(), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
